M48
; DRILL file {KiCad 7.0.8} date Thu Mar 28 15:32:12 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-28T15:32:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.765Y-2.295
X5.765Y-3.3975
X9.155Y-2.3125
X9.155Y-3.8475
T0
M30
